#!/usr/bin/tcsh
#PBS -c n
#PBS -r n
#PBS -p 20
#PBS -V
#PBS -N ijk.256.N4
#PBS -l mppwidth=256
#PBS -l mppnppn=4
#PBS -l walltime=02:00:00
#---PBS -q qcnodes
#PBS -j oe
#PBS -S /usr/bin/ksh
#
cd $PBS_O_WORKDIR
setenv DDI_DS_PER_NODE 1
setenv MPICH_PTL_MATCH_OFF 1
limit coredumpsize 512megabytes
aprun -n 256 -cc cpu ../triples-ijk.x | tee triples-ijk.$PBS_JOBID.log
rm -f triples-ijk.$PBS_JOBID.log
