#!/bin/tcsh

#make triples.x
module load craype-accel-nvidia20
module rm libsci_acc
module load gcc/4.5.3
#module list
make triples-cuda.x
#module load craype-accel-nvidia20
#module list
#make triples-acc.x
