C*MODULE CCAUX   *DECK VECCOP
      SUBROUTINE VECCOP(N,A,B)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(N),B(N)
C
      CALL DCOPY(N,B,1,A,1)
      RETURN
      END
C*MODULE CCAUX   *DECK INSI12
      SUBROUTINE INSI12(N1,N2,N3,TI,O2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION TI(N1,N2,N3),O2(N2,N1,N3)
C
      N=N1*N2*N3
      CALL VECCOP(N,TI,O2)
      DO 10 K=1,N3
      DO 10 I=1,N1
      DO 10 J=1,N2
      O2(J,I,K)=TI(I,J,K)
 10   CONTINUE
      RETURN
      END
C*MODULE CCAUX   *DECK INSI13
      SUBROUTINE INSI13(N1,N2,N3,TI,O2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION TI(N1,N2,N3),O2(N3,N2,N1)
C
      N=N1*N2*N3
      CALL VECCOP(N,TI,O2)
      DO 10 I=1,N1
      DO 10 J=1,N2
      DO 10 K=1,N3
      O2(K,J,I)=TI(I,J,K)
 10   CONTINUE
      RETURN
      END
C*MODULE CCAUX   *DECK INSI23
      SUBROUTINE INSI23(N1,N2,N3,TI,O2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION TI(N1,N2,N3),O2(N1,N3,N2)
C
      N=N1*N2*N3
      CALL VECCOP(N,TI,O2)
      DO 10 J=1,N2
      DO 10 K=1,N3
      DO 10 I=1,N1
      O2(I,K,J)=TI(I,J,K)
 10   CONTINUE
      RETURN
      END

